# Generated by Django 5.0.2 on 2024-02-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Date',
            fields=[
                ('pk_date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
    ]
