# Generated by Django 5.0.2 on 2024-02-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_d_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ods',
            name='nb_doses',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ods',
            name='nb_ucd',
            field=models.FloatField(),
        ),
    ]
