# Generated by Django 5.0.2 on 2024-02-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ods_nb_doses_alter_ods_nb_ucd'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Type',
            fields=[
                ('pk_type', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
