# Generated by Django 5.0.2 on 2024-02-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_d_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Geographie',
            fields=[
                ('pk_geographie', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('code_departement', models.IntegerField()),
                ('code_region', models.IntegerField()),
                ('label_departement', models.CharField(max_length=40)),
                ('label_region', models.CharField(max_length=3)),
            ],
        ),
    ]
