# Generated by Django 5.0.2 on 2024-02-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_d_geographie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_geographie',
            name='code_departement',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='d_geographie',
            name='code_region',
            field=models.CharField(max_length=3),
        ),
    ]
