# Generated by Django 5.0.2 on 2024-02-27 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_d_geographie_code_departement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='F_Dose',
            fields=[
                ('pk_dose', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nb_ucd', models.FloatField()),
                ('nb_doses', models.FloatField()),
                ('fk_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_date')),
                ('fk_geographie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_geographie')),
                ('fk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_type')),
            ],
        ),
    ]
