# Generated by Django 5.0.2 on 2024-03-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_f_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_dose',
            name='nb_doses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='f_dose',
            name='nb_ucd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
