# Generated by Django 5.0.2 on 2024-03-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_f_dose_nb_doses_alter_f_dose_nb_ucd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ods',
            name='nb_doses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ods',
            name='nb_ucd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
